### ISSUE TITLE
open event listener registration error

### ISSUE THREAD

**Issue by emarteca** [phodal/oculus-nodejs-threejs-example#2]
Hi all, I've been working on a tool to identify instances of events registered to the wrong object in uses of some JavaScript event-driven APIs, as part of a research project.
The tool flagged [line 63](https://github.com/phodal/oculus-nodejs-threejs-example/blob/master/index.js#L63) in index.js in the root of the repository, on the registration of the “open” event.

The reason I believe this is indicative of an error is as follows (from looking at the [npm ws API documentation](https://www.npmjs.com/package/ws)).
The wss variable, created on [line 60](https://github.com/phodal/oculus-nodejs-threejs-example/blob/master/index.js#L60) is an object of type ws.Server. However, the “open” event is emitter on ws.Socket. 

My guess is that your listener registration for “open” should be on the ws variable inside the listener for “connection” on [line 68](https://github.com/phodal/oculus-nodejs-threejs-example/blob/master/index.js#L68), since ws is a ws.Socket.

Thanks!

**Comment by phodal** [comment]
Hi @emarteca ,

I think this project code is old, you need to follow the API changes...

**Comment by emarteca** [comment]
Hey, thanks for the speedy response! I know the code is out of date, but I just want to see if this registration is actually incorrect, just to gauge the accuracy of my analysis tool.
Thanks again for your time!

**Comment by phodal** [comment]
Sorry, actually, I already lost some context in this project.

**Comment by emarteca** [comment]
Ok no worries. Thanks again for your time!
